import { Theme } from "theme.slint";
import { TabWidget , TabImpl} from "std-widgets.slint";
export { CustButton }

component CustButton inherits Rectangle {
    in property <bool> enabled: true;
    callback on_press();
    in property <string> text : "placeholder";
    border-width: 2px;

    text_comp := Text {
        text: text; 
        color: Theme.palette.main-text;
    }
    ta_comp := TouchArea {
        clicked => {parent.enabled? parent.on-press(): {};}
    }
    states [
        disabled when ! enabled: {
            background: Theme.palette.disabled-div;
            border-color: Theme.palette.disabled-border;
            text_comp.color: Theme.palette.disabled-text;
        } 
        resting when ! ta_comp.has-hover: {
            background: Theme.palette.main-div;
            border-color: Theme.palette.main-border;
            text_comp.color: Theme.palette.main-text;
        }
        hovered when ta_comp.has-hover: {
            background: Theme.palette.hovered-div;
            border-color: Theme.palette.hovered-border;
            text_comp.color: Theme.palette.hovered-text;
        }
        // pressed when shit_is_pressed i guess: {
        // }
    ]
    
}