struct Palette {
    font-fam: string,
    main-bg: brush,
    main-bg-grad: brush,

    main-div: brush,
    hovered-div: brush,
    pressed-div: brush,
    disabled-div: brush,

    main-border: brush,
    hovered-border: brush,
    pressed-border: brush,
    disabled-border: brush,

    main-text: brush,
    hovered-text: brush,
    pressed-text: brush,
    disabled-text: brush,
}

// Font candidates: "Sitka", "OCR A", "Candara", 
// "Cascadia Code", "Consolas", "HP Simplified", "Lucida Sans"
export global Theme {
    in property <Palette> palette: {
        font-fam: "OCR A Extended",
        main-bg: #121316,
        main-bg-grad: @radial-gradient(circle, #53668845 30%, #20242c1c 70%, #121316 100%),

        main-div: #03070dc0,
        hovered-div: #03070dc0.brighter(20%),
        pressed-div: #212329c0,
        disabled-div: #03070dc0.darker(90%),

        main-border: #2c333ec0,
        hovered-border: #2c333ec0.brighter(20%),
        pressed-border: #2c333ec0.brighter(100%),
        disabled-border: #2c333ec0.darker(90%),

        main-text: #b1c5f0,
        hovered-text: #b1c5f0.brighter(20%),
        pressed-text: #b1c5f0.brighter(80%),
        disabled-text: #b1c5f0.darker(90%),
    };
}