struct Palette {
    font-fam: string,
    main-bg: brush,
    main-bg-grad: brush,

    main-div: brush,
    hovered-div: brush,
    pressed-div: brush,
    disabled-div: brush,

    main-border: brush,
    hovered-border: brush,
    pressed-border: brush,
    disabled-border: brush,

    main-text: brush,
    hovered-text: brush,
    pressed-text: brush,
    disabled-text: brush,
}

// Font candidates: "Sitka", "OCR A", "Candara", 
// "Cascadia Code", "Consolas", "HP Simplified", "Lucida Sans"
export global Theme {
    in property <Palette> palette: {
        font-fam: "OCR A Extended",
        main-bg: #121316,
        main-bg-grad: @radial-gradient(circle, #0059ff45 30%, #0059ff00 80%),

        main-div: #1b212cc0,
        hovered-div: #1b212cc0.brighter(20%),
        pressed-div: #1b212cc0.darker(30%),
        disabled-div: #1b212cc0.darker(90%),

        main-border: #3b4557,
        hovered-border: #3b4557.brighter(20%),
        pressed-border: #3b4557.darker(30%),
        disabled-border: #3b4557.darker(90%),

        main-text: #b1c5f0,
        hovered-text: #b1c5f0.brighter(20%),
        pressed-text: #b1c5f0.darker(30%),
        disabled-text: #b1c5f0.darker(90%),
    };
}