struct Palette {
    main-bg: brush,

    main-div: brush,
    hovered-div: brush,
    pressed-div: brush,
    disabled-div: brush,

    main-border: brush,
    hovered-border: brush,
    pressed-border: brush,
    disabled-border: brush,

    main-text: brush,
    hovered-text: brush,
    pressed-text: brush,
    disabled-text: brush,
}

export global Theme {
    in property <Palette> palette: {
        main-bg: #293347,

        main-div: #152036,
        hovered-div: #152036.brighter(20%),
        pressed-div: #152036.darker(30%),
        disabled-div: #152036.darker(90%),

        main-border: #7e8695,
        hovered-border: #7e8695.brighter(20%),
        pressed-border: #7e8695.darker(30%),
        disabled-border: #7e8695.darker(90%),

        main-text: #c4d4f6,
        hovered-text: #c4d4f6.brighter(20%),
        pressed-text: #c4d4f6.darker(30%),
        disabled-text: #c4d4f6.darker(90%),
    };
}