import { Theme } from "theme.slint";
import { Logic } from "logic.slint";
export { FullTimer }


component Display inherits Rectangle {
    background: Theme.palette.main-div;
    in property <string> text: "--:--:--";
        Text {
            text: parent.text;
            color: Theme.palette.main-text;
         }
}

component TimerButton inherits Rectangle {
    callback on_press();
    background: Theme.palette.main-div;
    in property <string> text;
    Text {
        text: text; 
        color: Theme.palette.main-text;
    }
    area:= TouchArea { 
        clicked => {parent.on-press();}
    }
}

component FullTimer inherits Rectangle{
    
    VerticalLayout {
        spacing: 10px;
        height: 50%;
        width: 90%;
        
        display := Display {}

        HorizontalLayout {
            height: 30%;
            spacing: 10px;
            l_button := TimerButton {text: "Start Timer"; on-press => {Logic.press-l-button()}}
            r-button := TimerButton {text: "Reset Timer"; on-press => {Logic.press-r-button()}}
        }
    }
    states [
        inactive when !Logic.is-running : {
            l_button.text: "Start Timer";
            r_button.text: "Reset Timer (NR)";
            display.text: "--:--:--";
        }
        running when Logic.is-running && !Logic.is-paused : {
            l_button.text: "Start Timer";
            r_button.text: "Reset Timer (R)";
            display.text: Logic.time-str;
        }
        paused when Logic.is-running && Logic.is-paused : {
            l_button.text: "Start Timer";
            r_button.text: "Reset Timer (PR)";
            display.text: Logic.time-str;
        }

    ]
}